version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    restart: always

    working_dir: /tmp
    volumes:
      - /tmp
    networks:
      - app-network
    ports:
      - 10000:10000
    environment:
      - rabbbitUri=amqp://rabbitmq
      - host1=0.0.0.0
    links:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3.7.4
    networks:
      - app-network
    ports:
      - 5672:5672
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1:5672" ]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  app-network:
#    driver: bridge