version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /tmp
    volumes:
      - /tmp
    networks:
      - app-network
    ports:
      - 10000:10000
    environment:
      - rabbbitUri=amqp://rabbitmq
      - host1=0.0.0.0
    links:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3.7.4
    networks:
      - app-network
    ports:
      - 5672:5672

networks:
  app-network:
#    driver: bridge